env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  fast_finish: true
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8.1
notifications:
  email: false
script:
  - xcodebuild -scheme RateTVTests -project RateTV.xcodeproj -destination "name=Apple TV 1080p" test
